const express=require('express')
const cors=require('cors')
const mongoose=require('mongoose')
const user =require('./resolvers/user-resolver')
const company=require('./resolvers/company-resolver')
PORT=3000
mongoose.connect('mongodb+srv://deeznut:arminarlert@cluster0.sxhpz.mongodb.net/cse416?retryWrites=true&w=majority')

const app=express()
app.use(express.urlencoded({extended:true}))
app.use(cors())
app.use(express.json())
app.post('/user_register', user.register)
app.post('/user_login', user.login)
app.get(`/user_profile/:id`, user.getUser)
app.post('/company_register', company.register)
app.listen(PORT, ()=>{console.log(`app is listening in ${PORT}`)})